# http://localhost:8080/actuator/gateway/routes
server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    # A client sends a request to Spring Cloud Gateway. If the request matches a route through its predicates, the Gateway HandlerMapping will send the request to the Gateway WebHandler, which in turn will run the request through a chain of filters.
    gateway:
      # For automatic route discovery through Eureka
      discovery.locator:
        enabled: false
        lowerCaseServiceId: true
      # Route. It?s identified by a unique ID, a collection of predicates deciding whether to follow the route, a URI for forwarding the request if the predicates allow, and a collection of filters applied either before or after forwarding the request downstream.
      routes:
        - id: bookmodule
          uri: lb://BOOKMS
          predicates:
            - Path=/bookms/**
          filters:
            - RewritePath=/bookms/(?<path>.*), /$\{path}
        - id: issuermodule
          uri: lb://ISSUERMS
          predicates:
            - Path=/issuerms/**
          filters:
            - RewritePath=/issuerms/(?<path>.*), /$\{path}
            

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.netflix: WARN
    org.springframework.web: DEBUG
    com.amazingapp: DEBUG